# Generated by Django 2.1.7 on 2019-04-04 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[('EVENT1', 'EVENT1'), ('EVENT2', 'EVENT2'), ('EVENT3', 'EVENT3'), ('EVENT4', 'EVENT4'), ('EVENT5', 'EVENT5'), ('EVENT6', 'EVENT6'), ('EVENT7', 'EVENT7'), ('EVENT8', 'EVENT8'), ('EVENT9', 'EVENT9'), ('EVENT10', 'EVENT10')], help_text='Enter Event Name (e.g. CodeGolf)', max_length=200)),
                ('summary', models.TextField(default='', help_text='Enter a brief description of the event', max_length=1000)),
            ],
            options={
                'ordering': ['event_type', 'event_name'],
            },
        ),
        migrations.CreateModel(
            name='Event_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TECHNICAL', 'TECHNICAL'), ('NON-TECHNICAL', 'NON-TECHNICAL')], help_text='Enter Event Type (e.g. Tech)', max_length=200)),
            ],
            options={
                'ordering': ['event_type'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='+919999999999', max_length=128, region=None, unique=True)),
                ('year', models.CharField(choices=[('first', '1'), ('second', '2'), ('third', '3'), ('forth', '4')], default='first', max_length=10)),
                ('payment_status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ManyToManyField(to='account.Event')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Event_Type'),
        ),
    ]
